begin;
lock table auth.users,auth.sessions,auth.identities,auth.refresh_tokens,public.games,public.game_members,public.game_cells,public.game_events,public.game_question_usage,public.match_results,public.authorized_devices,public.couple_admins,private.online_player_identities,private.online_player_attempts,private.online_player_codes in share row exclusive mode;
create temporary table online_cleanup_result(report jsonb) on commit preserve rows;
do $cleanup$
declare v_users uuid[]:=array['94bec68f-2b76-47a3-92a3-2488f8b07de3'::uuid,'9b3c0666-af39-4fb1-bb83-5f4c5b007781'::uuid,'4489e84e-b4b6-4300-ab2a-344bfbad1e43'::uuid,'190e4385-6e80-4c73-8820-3c85876ee339'::uuid,'83422d2d-f5f9-4c1a-9f7f-cda8bda62bbe'::uuid,'8e99affa-3299-4f57-87f4-bce719ececfd'::uuid]::uuid[];v_games uuid[]:=array['1ba0205e-24e5-4d34-85cd-a529d7abf0b5'::uuid,'9f1cd7af-0517-489d-ada6-cfc3809dd5c1'::uuid]::uuid[];v_before jsonb;v_after jsonb;v_deleted_games integer;v_deleted_users integer;
begin
if exists(select 1 from auth.users where id=any(v_users) and is_anonymous is distinct from true) or exists(select 1 from public.couple_admins where user_id=any(v_users)) or exists(select 1 from public.authorized_devices where user_id=any(v_users)) then raise exception 'QA_SCOPE_CONTAINS_PROTECTED_USER';end if;
if exists(select 1 from public.games where created_by=any(v_users) and not(id=any(v_games))) or exists(select 1 from public.game_members where user_id=any(v_users) and not(game_id=any(v_games))) or exists(select 1 from public.games where id=any(v_games) and not(created_by=any(v_users))) or exists(select 1 from public.game_members where game_id=any(v_games) and not(user_id=any(v_users))) then raise exception 'QA_SCOPE_CONTAINS_UNLISTED_GAME_OR_MEMBER';end if;
if exists(select 1 from public.games where id=any(v_games) and status<>'ABANDONED') or exists(select 1 from public.match_results where game_id=any(v_games)) then raise exception 'QA_GAMES_NOT_ABANDONED_OR_HAVE_RESULTS';end if;
select jsonb_build_object('games',(select md5(coalesce(string_agg(to_jsonb(g)::text,'' order by id),'')) from public.games g where not(id=any(v_games))),'users',(select md5(coalesce(string_agg(to_jsonb(u)::text,'' order by id),'')) from auth.users u where not(id=any(v_users))),'results',(select md5(coalesce(string_agg(to_jsonb(r)::text,'' order by id),'')) from public.match_results r),'identities',(select md5(coalesce(string_agg(to_jsonb(i)::text,'' order by user_id),'')) from private.online_player_identities i where not(user_id=any(v_users))),'codes',(select md5(coalesce(string_agg(to_jsonb(c)::text,'' order by player_role),'')) from private.online_player_codes c),'devices',(select md5(coalesce(string_agg(to_jsonb(d)::text,'' order by id),'')) from public.authorized_devices d)) into v_before;
delete from public.games where id=any(v_games);get diagnostics v_deleted_games=row_count;
delete from auth.users where id=any(v_users);get diagnostics v_deleted_users=row_count;
select jsonb_build_object('games',(select md5(coalesce(string_agg(to_jsonb(g)::text,'' order by id),'')) from public.games g where not(id=any(v_games))),'users',(select md5(coalesce(string_agg(to_jsonb(u)::text,'' order by id),'')) from auth.users u where not(id=any(v_users))),'results',(select md5(coalesce(string_agg(to_jsonb(r)::text,'' order by id),'')) from public.match_results r),'identities',(select md5(coalesce(string_agg(to_jsonb(i)::text,'' order by user_id),'')) from private.online_player_identities i where not(user_id=any(v_users))),'codes',(select md5(coalesce(string_agg(to_jsonb(c)::text,'' order by player_role),'')) from private.online_player_codes c),'devices',(select md5(coalesce(string_agg(to_jsonb(d)::text,'' order by id),'')) from public.authorized_devices d)) into v_after;
if v_before is distinct from v_after then raise exception 'CLEANUP_CHANGED_UNLISTED_DATA';end if;
if exists(select 1 from auth.users where id=any(v_users)) or exists(select 1 from public.games where id=any(v_games)) or exists(select 1 from private.online_player_identities where user_id=any(v_users)) then raise exception 'QA_FIXTURES_REMAIN';end if;
insert into online_cleanup_result values(jsonb_build_object('status','PASS','deletedQaUsers',v_deleted_users,'deletedQaGames',v_deleted_games,'unlistedDataUnchanged',true,'privateCodesPreserved',true,'remainingQaUsers',0,'remainingQaGames',0,'remainingQaIdentities',0));
end;$cleanup$;
commit;
select report from online_cleanup_result;