import approved from '../../data/copy_ca.json';

export const ca = {
  ...approved,
  tagline: 'Preguntes, torns i brindis.',
  homeEyebrow: 'EL JOC DE TAULA I DE BEURE',
  loading: 'Preparem la taula…',
  sending: 'Un moment…',
  next: 'Continuar',
  back: 'Enrere',
  chooseRole: 'Qui ets?',
  chooseOnline: 'Preparem la trobada',
  customMinutes: 'Durada en minuts (10–60)',
  durationHelp: 'Estimació amb torns de 30 segons. Jugueu al vostre ritme.',
  waitingPlayer: 'Escolta la resposta i decideix.',
  waitingStart: 'Espereu que tots dos sigueu aquí.',
  claimPau: 'En Pau respon!',
  claimTecla: 'La Tecla respon!',
  checking: 'Comprovant…',
  finishedHelp: 'Una partida més per recordar.',
  abandoned: 'Heu deixat la partida',
  noPoint: 'El marcador no ha canviat.',
  copied: 'Codi copiat',
  copyUnavailable: 'Podeu seleccionar i copiar el codi de la partida.',
  inviteHelp: 'Comparteix aquest codi amb l’altra persona.',
  connectionRetry: 'Torna-ho a provar',
  connectionNeeded: 'Cal connexió per continuar la partida.',
  setupMissing: 'Cal configurar la connexió al joc.',
  deviceUnavailable: 'Aquest dispositiu encara no està autoritzat.',
  ruleGoal: 'Guanya qui arriba primer a Meta.',
  ruleTalk: 'Responeu sempre en veu alta. L’altra persona fa de jutge.',
  ruleCorrect: 'Si encertes, avances una casella. Si falles, no avances, perds el torn i beus.',
  ruleBonus: 'A +1, un encert avança una casella extra; un error vol dir beure doble.',
  ruleTP: 'A T&P, respon qui reclama primer. En línia ho confirma el servidor.',
  ruleScore: 'Només les partides que arriben a Meta compten al marcador.',
  ruleCategories: 'Personal tracta dels vostres àmbits; Creuada, dels de l’altra persona.',
  close: 'Tancar',
  exit: 'Sortir',
  showRules: 'Llegir les normes',
  questionReady: 'La següent casella us espera.',
  turnLabel: 'Torn',
  boardLabel: 'Tauler de joc',
  personalLabel: 'Personal',
  crossedLabel: 'Creuada',
  noSecondAttempt: 'Aquesta pregunta no té segon intent.',
  versionChanged: 'La partida s’ha actualitzat.',
} as const;

export const errorMessages: Record<string, string> = {
  INVALID_CODE: 'El codi no és correcte.',
  invalid_code: 'El codi no és correcte.',
  RATE_LIMITED: 'Massa intents. Espereu una estona abans de tornar-hi.',
  ACCESS_RATE_LIMITED: 'Massa intents. Espereu una estona abans de tornar-hi.',
  PUBLIC_GAME_NOT_CONFIGURED: 'Cal configurar la connexió al joc.',
  ANONYMOUS_DISABLED: 'Cal activar l’accés anònim al servidor del joc.',
  NOT_AUTHENTICATED: 'Cal tornar a entrar al joc.',
  DEVICE_NOT_AUTHORIZED: 'Aquest dispositiu encara no està autoritzat.',
  NOT_GAME_MEMBER: 'Aquest dispositiu no forma part de la partida.',
  NOT_A_GAME_MEMBER: 'Aquest dispositiu no forma part de la partida.',
  ROLE_ALREADY_TAKEN: 'Aquest lloc ja està ocupat.',
  GAME_NOT_JOINABLE: 'Aquesta partida ja no admet participants.',
  GAME_NOT_FOUND: 'No hem trobat aquesta partida.',
  INVALID_PHASE: 'Aquesta acció no correspon al moment de la partida.',
  ACTION_NOT_ALLOWED: 'Ara no pots fer aquesta acció.',
  NOT_ALLOWED: 'Ara no pots fer aquesta acció.',
  CLAIM_CLOSED: 'Ha respost primer l’altra persona.',
  CLAIMANT_MISMATCH: 'Cal reclamar amb el teu propi rol.',
  BOTH_PLAYERS_REQUIRED: 'Cal que tots dos sigueu a la partida.',
  IDEMPOTENCY_KEY_REUSED: 'Aquesta acció ja s’ha enviat.',
  STALE_STATE: ca.versionChanged,
  QUESTION_POOL_EMPTY: 'S’han acabat les preguntes d’aquesta categoria.',
  GAME_ALREADY_FINISHED: 'Aquesta partida ja s’ha acabat.',
  CONNECTION_REQUIRED: ca.connectionNeeded,
  RESPONSE_INVALID: 'No hem pogut recuperar la partida. Torna-ho a provar.',
};

export function errorInCatalan(error: unknown): string {
  const message = error instanceof Error ? error.message :
    error && typeof error === 'object' && 'message' in error && typeof error.message === 'string' ? error.message : '';
  const code = Object.keys(errorMessages).find((candidate) => message.includes(candidate));
  return code ? errorMessages[code] : 'No hem pogut connectar amb el joc. Torna-ho a provar.';
}
