export const ca = {
  appTitle: "Pau & Tecla",
  playInPerson: "Jugar en persona",
  playOnline: "Jugar en línia",
  rules: "Normes",
  durationQuestion: "Quant de temps voleu que duri la partida?",
  whoStarts: "Qui comença?",
  pau: "Pau",
  tecla: "Tecla",
  random: "A l’atzar",
  showAnswer: "Mostra la resposta",
  correctAnswer: "Resposta correcta",
  correct: "Correcte",
  incorrect: "Incorrecte",
  nextTurn: "Següent torn",
  turnPau: "Torn d’en Pau",
  turnTecla: "Torn de la Tecla",
  answerAloud: "Respon en veu alta!",
  iAnswer: "Jo responc!",
  drink: "Beu.",
  drinkDouble: "Beu doble.",
  start: "Sortida",
  finish: "Meta",
  connectionLost: "S’ha perdut la connexió",
  reconnecting: "S’està reconnectant…",
  reconnected: "T’has tornat a connectar",
  gameContinues: "La partida continua.",
  pauWon: "Ha guanyat en Pau!",
  teclaWon: "Ha guanyat la Tecla!",
} as const;
