-- Exactly 130 approved questions from data/questions_approved.json.
insert into public.questions (id, pool, topic, difficulty, question_ca, answer_ca, review_status, factual_reviewed, language_reviewed, active, source_type, notes, content_version, approved_at) values
('pau_001', 'PAU', 'Programació', 2, 'Quin tipus de variable només pot tenir dos valors?', 'Booleana', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_002', 'PAU', 'Estructures de dades', 2, 'Quina estructura segueix l’ordre LIFO?', 'Pila', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_003', 'PAU', 'Bases de dades', 1, 'Quin llenguatge s’utilitza per consultar bases de dades relacionals?', 'SQL', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_004', 'PAU', 'Bases de dades', 2, 'Com s’anomena el camp que identifica unívocament una fila?', 'Clau primària', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_005', 'PAU', 'Programació', 2, 'Com s’anomena una funció que es crida a si mateixa?', 'Recursiva', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_006', 'PAU', 'Algorismes', 3, 'Quin algorisme troba camins mínims amb pesos no negatius?', 'Dijkstra', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_007', 'PAU', 'Dades', 1, 'Quin format de text representa dades amb claus i valors?', 'JSON', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_008', 'PAU', 'SQL', 2, 'Quina clàusula SQL filtra files?', 'WHERE', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_009', 'PAU', 'SQL', 2, 'Quin JOIN conserva només les coincidències?', 'INNER JOIN', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_010', 'PAU', 'Desenvolupament', 1, 'Quin sistema s’utilitza habitualment per controlar versions?', 'Git', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_011', 'PAU', 'Dades', 2, 'Quina biblioteca de Python treballa amb DataFrames?', 'pandas', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_012', 'PAU', 'Dades', 3, 'Quin motor distribuït és habitual en processos ETL massius?', 'Apache Spark', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_013', 'PAU', 'Informàtica', 1, 'Quina és la unitat mínima d’informació digital?', 'Bit', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_014', 'PAU', 'Web', 2, 'Quin protocol protegeix habitualment una connexió web?', 'HTTPS', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_015', 'PAU', 'Programació', 2, 'Quina estructura associa claus amb valors?', 'Diccionari', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_016', 'PAU', 'Geografia', 2, 'Quin meridià marca la longitud zero?', 'Greenwich', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_017', 'PAU', 'Geografia', 1, 'Quin és l’oceà més gran del planeta?', 'Pacífic', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_018', 'PAU', 'Geografia', 1, 'Quin riu travessa Egipte?', 'Nil', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_019', 'PAU', 'Geografia', 2, 'Quina és la muntanya més alta d’Àfrica?', 'Kilimanjaro', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_020', 'PAU', 'Geografia', 2, 'Quin estret separa Europa d’Àfrica?', 'Gibraltar', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_021', 'PAU', 'Atletisme', 1, 'Quants metres té una volta a una pista exterior estàndard?', '400 metres', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_022', 'PAU', 'Atletisme', 1, 'Quina prova equival a dues voltes de pista?', '800 metres', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_023', 'PAU', 'Biologia', 2, 'Quin orgànul produeix gran part de l’energia cel·lular?', 'Mitocondri', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_024', 'PAU', 'Natura', 1, 'Quin és l’animal terrestre més ràpid?', 'Guepard', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_025', 'PAU', 'Geologia', 2, 'Quina capa líquida envolta el nucli intern terrestre?', 'Nucli extern', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('pau_026', 'PAU', 'Geografia', 2, 'Quina serralada conté l’Everest?', 'Himàlaia', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_001', 'TECLA', 'Anatomia', 1, 'Quina és l’artèria més gran del cos humà?', 'Aorta', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_002', 'TECLA', 'Anatomia', 2, 'Quina cavitat impulsa la sang cap a tot el cos?', 'Ventricle esquerre', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_003', 'TECLA', 'Fisiologia', 2, 'Quina proteïna transporta oxigen a la sang?', 'Hemoglobina', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_004', 'TECLA', 'Tecnologia mèdica', 2, 'Quin instrument mesura la pressió arterial?', 'Esfigmomanòmetre', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_005', 'TECLA', 'Imatge mèdica', 2, 'Quina tècnica utilitza camps magnètics per obtenir imatges?', 'Ressonància magnètica', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_006', 'TECLA', 'Diagnòstic', 2, 'Com s’anomena el registre elèctric del cor?', 'Electrocardiograma', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_007', 'TECLA', 'Biologia cel·lular', 3, 'Quina cèl·lula forma teixit ossi?', 'Osteoblast', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_008', 'TECLA', 'Física', 1, 'Quina unitat mesura la freqüència?', 'Hertz', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_009', 'TECLA', 'Música', 1, 'Quina nota s’utilitza habitualment per afinar una orquestra?', 'La', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_010', 'TECLA', 'Cant', 1, 'Quina és la veu femenina més aguda?', 'Soprano', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_011', 'TECLA', 'Cant', 1, 'Quina és la veu masculina més greu?', 'Baix', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_012', 'TECLA', 'Cant coral', 1, 'Com s’anomena un conjunt de persones que canten juntes?', 'Cor', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_013', 'TECLA', 'Cant coral', 2, 'Qui coordina musicalment una coral?', 'Director de cor', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_014', 'TECLA', 'Música catalana', 1, 'Quin instrument de vent és típic de la cobla?', 'Tenora', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_015', 'TECLA', 'Música', 1, 'Quantes línies té un pentagrama?', 'Cinc', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_016', 'TECLA', 'Música', 2, 'Quin símbol eleva una nota un semitò?', 'Sostingut', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_017', 'TECLA', 'Folklore català', 1, 'Quin ball tradicional utilitza bastons?', 'Ball de bastons', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_018', 'TECLA', 'Folklore català', 1, 'Quin instrument acompanya sovint els balls populars catalans?', 'Gralla', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_019', 'TECLA', 'Sitges', 2, 'Com s’anomena popularment l’església emblemàtica del Baluard?', 'La Punta', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_020', 'TECLA', 'Sitges', 2, 'Quina santa protagonitza la festa sitgetana de setembre?', 'Santa Tecla', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_021', 'TECLA', 'Folklore', 1, 'Quin element festiu acostuma a treure foc per la boca?', 'Drac', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_022', 'TECLA', 'Indumentària', 1, 'Quin calçat tradicional català té sola d’espart?', 'Espardenyes', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_023', 'TECLA', 'Anatomia', 1, 'Quins òrgans filtren la sang i produeixen orina?', 'Ronyons', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_024', 'TECLA', 'Anatomia', 2, 'Quina vàlvula separa l’aurícula i el ventricle esquerres?', 'Mitral', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_025', 'TECLA', 'Biomedicina', 2, 'Quin dispositiu substitueix el ritme cardíac quan cal?', 'Marcapassos', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tecla_026', 'TECLA', 'Cant', 2, 'Quina veu femenina se situa entre soprano i contralt?', 'Mezzosoprano', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tpau_001', 'TECLA_PAU', 'Informàtica fàcil', 1, 'Quin valor pot tenir una variable booleana?', 'Cert o fals', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tpau_002', 'TECLA_PAU', 'Programació fàcil', 1, 'Quina extensió tenen habitualment els fitxers de Python?', '.py', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tpau_003', 'TECLA_PAU', 'Dades fàcil', 1, 'Quin llenguatge serveix per consultar una base de dades?', 'SQL', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tpau_004', 'TECLA_PAU', 'Internet', 1, 'Quin aparell dirigeix trànsit entre xarxes?', 'Encaminador', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tpau_005', 'TECLA_PAU', 'Desenvolupament', 1, 'Quina eina guarda l’historial de canvis del codi?', 'Git', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tpau_006', 'TECLA_PAU', 'Dades', 1, 'Quin gràfic mostra punts en dos eixos numèrics?', 'Gràfic de dispersió', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tpau_007', 'TECLA_PAU', 'Informàtica', 1, 'En quina unitat s’expressa sovint la freqüència d’un processador?', 'GHz', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tpau_008', 'TECLA_PAU', 'Atletisme', 1, 'Quants metres té una volta de pista?', '400 metres', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tpau_009', 'TECLA_PAU', 'Atletisme', 1, 'Quina prova corre principalment en Pau?', '800 metres', 'APPROVED', true, true, true, 'user_provided', '', 1, now()),
('tpau_010', 'TECLA_PAU', 'Atletisme', 1, 'A quin grup de proves pertanyen els 800 metres?', 'Mig fons', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tpau_011', 'TECLA_PAU', 'Geografia', 1, 'En quin continent es troba Kenya?', 'Àfrica', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tpau_012', 'TECLA_PAU', 'Geografia', 1, 'Quin és el país més extens del món?', 'Rússia', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tpau_013', 'TECLA_PAU', 'Geografia', 1, 'Quin oceà banya la costa oriental d’Àfrica?', 'Índic', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tpau_014', 'TECLA_PAU', 'Geografia', 1, 'Quina és la capital de França?', 'París', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tpau_015', 'TECLA_PAU', 'Geografia', 1, 'Quin riu travessa Londres?', 'Tàmesi', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tpau_016', 'TECLA_PAU', 'Geografia', 1, 'Quina línia imaginària divideix la Terra en nord i sud?', 'Equador', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tpau_017', 'TECLA_PAU', 'Natura', 1, 'Quin és l’animal terrestre més gran?', 'Elefant africà', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tpau_018', 'TECLA_PAU', 'Astronomia', 1, 'Quin planeta és conegut com el planeta vermell?', 'Mart', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tpau_019', 'TECLA_PAU', 'Natura', 1, 'Com s’anomena el procés amb què les plantes aprofiten la llum?', 'Fotosíntesi', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tpau_020', 'TECLA_PAU', 'Personal', 1, 'En quin camp treballa en Pau?', 'Dades', 'APPROVED', true, true, true, 'user_provided', '', 1, now()),
('tpau_021', 'TECLA_PAU', 'Personal', 1, 'Quin esport practica en Pau?', 'Atletisme', 'APPROVED', true, true, true, 'user_provided', '', 1, now()),
('tpau_022', 'TECLA_PAU', 'Personal', 1, 'Quina branca esportiva practica principalment en Pau?', 'Mig fons', 'APPROVED', true, true, true, 'user_provided', '', 1, now()),
('tpau_023', 'TECLA_PAU', 'Algorismes fàcil', 1, 'Què calcula l’algorisme de Dijkstra?', 'Camí més curt', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tpau_024', 'TECLA_PAU', 'Natura', 1, 'Quina revista inspira especialment els interessos naturals d’en Pau?', 'National Geographic', 'APPROVED', true, true, true, 'user_provided', '', 1, now()),
('tpau_025', 'TECLA_PAU', 'Geografia', 1, 'Quin mar separa Europa del nord d’Àfrica?', 'Mediterrani', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('tpau_026', 'TECLA_PAU', 'Dades', 1, 'Com s’anomena una taula de dades a pandas?', 'DataFrame', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('ptecla_001', 'PAU_TECLA', 'Personal', 1, 'Quina professió té la Tecla?', 'Enginyera biomèdica', 'APPROVED', true, true, true, 'user_provided', '', 1, now()),
('ptecla_002', 'PAU_TECLA', 'Personal', 1, 'De quin municipi és la Tecla?', 'Sitges', 'APPROVED', true, true, true, 'user_provided', '', 1, now()),
('ptecla_003', 'PAU_TECLA', 'Personal', 1, 'Quina activitat artística practica la Tecla?', 'Cant', 'APPROVED', true, true, true, 'user_provided', '', 1, now()),
('ptecla_004', 'PAU_TECLA', 'Personal', 1, 'En quin tipus de grup ha cantat la Tecla?', 'Coral', 'APPROVED', true, true, true, 'user_provided', '', 1, now()),
('ptecla_005', 'PAU_TECLA', 'Anatomia fàcil', 1, 'Quina és l’artèria més gran del cos?', 'Aorta', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('ptecla_006', 'PAU_TECLA', 'Anatomia fàcil', 1, 'Quin òrgan impulsa la sang?', 'Cor', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('ptecla_007', 'PAU_TECLA', 'Anatomia fàcil', 1, 'Quants ossos té habitualment un adult?', '206', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('ptecla_008', 'PAU_TECLA', 'Anatomia fàcil', 1, 'Com s’anomenen els glòbuls vermells?', 'Eritròcits', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('ptecla_009', 'PAU_TECLA', 'Cant fàcil', 1, 'Quina és la veu femenina més aguda?', 'Soprano', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('ptecla_010', 'PAU_TECLA', 'Cant fàcil', 1, 'Com s’anomena un grup de persones que canten juntes?', 'Cor', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('ptecla_011', 'PAU_TECLA', 'Música catalana', 1, 'Quin instrument és típic de la cobla?', 'Tenora', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('ptecla_012', 'PAU_TECLA', 'Música fàcil', 1, 'Quantes línies té un pentagrama?', 'Cinc', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('ptecla_013', 'PAU_TECLA', 'Música fàcil', 1, 'Com s’anomena un signe que indica absència de so?', 'Silenci', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('ptecla_014', 'PAU_TECLA', 'Folklore català', 1, 'Quina dansa catalana es balla en rotllana?', 'Sardana', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('ptecla_015', 'PAU_TECLA', 'Folklore català', 1, 'Quin ball tradicional utilitza bastons?', 'Ball de bastons', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('ptecla_016', 'PAU_TECLA', 'Folklore català', 1, 'Quin instrument sona sovint als balls populars?', 'Gralla', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('ptecla_017', 'PAU_TECLA', 'Sitges', 1, 'Com s’anomena popularment l’església del Baluard?', 'La Punta', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('ptecla_018', 'PAU_TECLA', 'Folklore', 1, 'Quin element festiu treu foc per la boca?', 'Drac', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('ptecla_019', 'PAU_TECLA', 'Sitges', 1, 'Quina santa dona nom a la festa de setembre?', 'Santa Tecla', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('ptecla_020', 'PAU_TECLA', 'Indumentària', 1, 'Quin calçat tradicional té sola d’espart?', 'Espardenyes', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('ptecla_021', 'PAU_TECLA', 'Biomedicina', 1, 'Quina enginyeria uneix tecnologia i salut?', 'Enginyeria biomèdica', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('ptecla_022', 'PAU_TECLA', 'Imatge mèdica', 1, 'Quina tècnica utilitza raigs X per fer una imatge?', 'Radiografia', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('ptecla_023', 'PAU_TECLA', 'Diagnòstic', 1, 'Quina prova registra l’activitat elèctrica del cor?', 'Electrocardiograma', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('ptecla_024', 'PAU_TECLA', 'Cant', 1, 'Quina és la veu femenina més greu?', 'Contralt', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('ptecla_025', 'PAU_TECLA', 'Anatomia', 1, 'Quins òrgans permeten respirar?', 'Pulmons', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('ptecla_026', 'PAU_TECLA', 'Música', 1, 'Quina nota segueix el do?', 'Re', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_001', 'TP', 'Catalunya', 1, 'Quina és la capital de Catalunya?', 'Barcelona', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_002', 'TP', 'Catalunya', 2, 'Quin és el cim més alt de Catalunya?', 'Pica d’Estats', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_003', 'TP', 'Geografia', 1, 'Quin mar banya la costa catalana?', 'Mediterrani', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_004', 'TP', 'Llengua', 1, 'Quina és la llengua oficial pròpia d’Andorra?', 'Català', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_005', 'TP', 'Folklore català', 1, 'Quina dansa catalana es balla en rotllana?', 'Sardana', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_006', 'TP', 'Música catalana', 1, 'Quin instrument és característic de la cobla?', 'Tenora', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_007', 'TP', 'Art', 1, 'Qui va pintar el Guernica?', 'Picasso', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_008', 'TP', 'Astronomia', 1, 'Quin és el planeta més gran del sistema solar?', 'Júpiter', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_009', 'TP', 'Ciència', 1, 'Quin gas absorbeixen les plantes durant la fotosíntesi?', 'Diòxid de carboni', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_010', 'TP', 'Ciència', 1, 'Quina és la fórmula química de l’aigua?', 'H₂O', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_011', 'TP', 'Animals', 1, 'Quin mamífer pot volar?', 'Ratpenat', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_012', 'TP', 'Geografia', 1, 'Quin és l’oceà més gran?', 'Pacífic', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_013', 'TP', 'Geografia', 1, 'En quin continent es troba el Sàhara?', 'Àfrica', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_014', 'TP', 'Geografia', 1, 'Com s’anomena una línia de longitud terrestre?', 'Meridià', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_015', 'TP', 'Literatura', 2, 'Qui va escriure El petit príncep?', 'Antoine de Saint-Exupéry', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_016', 'TP', 'Música', 1, 'Qui va compondre Les quatre estacions?', 'Vivaldi', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_017', 'TP', 'Anatomia', 1, 'Quants ossos té habitualment un adult?', '206', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_018', 'TP', 'Ciència', 1, 'Quin metall és líquid a temperatura ambient?', 'Mercuri', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_019', 'TP', 'Mineralogia', 1, 'Quin és el mineral natural més dur?', 'Diamant', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_020', 'TP', 'Anatomia', 1, 'Quin és l’òrgan més gran del cos humà?', 'Pell', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_021', 'TP', 'Geografia', 1, 'Quin país europeu té forma de bota?', 'Itàlia', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_022', 'TP', 'Geografia', 1, 'Quin riu travessa París?', 'Sena', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_023', 'TP', 'Geografia', 1, 'Quina serralada conté l’Everest?', 'Himàlaia', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_024', 'TP', 'Música', 1, 'Quin instrument té tecles, cordes i pedals?', 'Piano', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_025', 'TP', 'Història', 1, 'Quina civilització va construir el Colosseu?', 'Romans', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now()),
('common_026', 'TP', 'Natura', 1, 'Quin arbre produeix olives?', 'Olivera', 'APPROVED', true, true, true, 'general_knowledge', '', 1, now())
on conflict (id) do update set
pool=excluded.pool,
topic=excluded.topic,
difficulty=excluded.difficulty,
question_ca=excluded.question_ca,
answer_ca=excluded.answer_ca,
review_status=excluded.review_status,
factual_reviewed=excluded.factual_reviewed,
language_reviewed=excluded.language_reviewed,
active=excluded.active,
source_type=excluded.source_type,
notes=excluded.notes,
content_version=excluded.content_version,
approved_at=excluded.approved_at;
